/* empty css                      */import{S as h,A as g}from"./assets/vendor-16iyBIrI.js";(function(){const c=document.createElement("link").relList;if(c&&c.supports&&c.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();let f=null;function p(){const s=window.innerWidth>=1440;if(s&&f){f.destroy(!0,!0),f=null;return}!s&&!f&&(f=new h(".my-swiper",{modules:[g],loop:!0,speed:6e3,allowTouchMove:!1,grabCursor:!1,slidesPerView:1,spaceBetween:20,autoplay:{delay:0,disableOnInteraction:!1,pauseOnMouseEnter:!1}}))}p();window.addEventListener("resize",p);document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),c=s.querySelector(".icon"),u=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const l=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 36V33H42V36H6ZM6 25.5V22.5H42V25.5H6ZM6 15V12H42V15H6Z" fill="#5EE6A8" />
</svg>
    `,o=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#5EE6A8" />
</svg>
    `;s.addEventListener("click",()=>{t=!t,c.innerHTML=t?o:l,t?n():r()}),a.forEach(d=>d.addEventListener("click",()=>{r(),c.innerHTML=l,t=!1})),window.addEventListener("scroll",i);function n(){u.style.display="block"}function r(){u.style.display="none"}function i(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function s(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function c(o){const n=document.getElementById(o);if(!n)return;const r=s(),i=n.getBoundingClientRect().top+window.pageYOffset-r;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(n){const r=this.getAttribute("href");if(!r)return;const[i,d]=r.split("#");if(!d)return;const m=window.location.pathname.split("/").pop();!(i===""||i==="./"||i===m||i==="./"+m)||!document.getElementById(d)||(n.preventDefault(),c(d),t(d))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(r=>r.classList.remove("active"));const n=document.querySelector(`.navigation-item a[href*="#${o}"]`);n&&n.closest(".navigation-item").classList.add("active")}function l(){const o=window.pageYOffset+s()+100;a.forEach(n=>{const r=n.offsetTop,i=r+n.offsetHeight;o>=r&&o<i&&t(n.id)})}if(window.addEventListener("scroll",l),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{c(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
